

export const db = [
    {
        id:0,
        difficulty:1,
        category:'Sorting',
        successfulSubmission: 1235,
        title:'Bubble Sort',
        description:'Bubble is a sorting algorithm that...',
        hints:[{text:'try'}, {text:'harder'}],
        solutions:[{text:'sol 1', price:120, _id:0}, {text:'sol 2', price:120, _id:1}], 
        inputCode:'function bubbleSort(array) ...',
        outputCode:'',
        solutionDefault:'',
        maxEXP:1000,
    }, 
    {
        id:1,
        difficulty:1,
        category:'Sorting',
        successfulSubmission:32454,
        title:'Merge Sort',
        description:'Merge is a sorting algorithm that...',
        hints:[{text:'try'}, {text:'harder'}],
        solutions:[{text:'sol 1', price:120, _id:0}, {text:'sol 2', price:120, _id:1}], 
        inputCode:'function bubbleSort(array) ...',
        outputCode:'',
        solutionDefault:'',
        maxEXP:1000,
    },
    {
        id:2,
        difficulty:1,
        category:'Sorting',
        successfulSubmission:1235,
        title:'Quick Sort',
        description:'Quick is a sorting algorithm that...',
        hints:[{text:'try'}, {text:'harder'}],
        solutions:[{text:'sol 1', price:120, _id:0}, {text:'sol 2', price:120, _id:1}], 
        inputCode:'function bubbleSort(array) ...',
        outputCode:'',
        solutionDefault:'',
        maxEXP:1000,
    }, 
    {
        id:3,
        difficulty:3,
        category:'Algorithms',
        successfulSubmission:524,
        title:'DFS',
        description:'dfs is a searching algorithm',
        hints:[{text:'try'}, {text:'harder'}],
        solutions:[{text:'sol 1', price:120, _id:0}, {text:'sol 2', price:120, _id:1}], 
        inputCode:'function bubbleSort(array) ...',
        outputCode:'',
        solutionDefault:'',
        maxEXP:4000,
    },
    {
        id:4,
        difficulty:3,
        category:'Algorithms',
        successfulSubmission:145,
        title:'BFS',
        description:'bfs is a searching algorithm',
        hints:[{text:'try'}, {text:'harder'}, {text:'and harder'}],        
        solutions:[{text:'sol 1', price:120, _id:0}, {text:'sol 2', price:120, _id:1}], 
        inputCode:'function bubbleSort(array) ...',
        outputCode:'',
        solutionDefault:'',
        maxEXP:4000,
    },
]